ishop/ishop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from store import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^store/', include('store.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special'),
    url('search/',views.search,name="search"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ishop/store/urls.py
from django.conf.urls import url
from store import views



#Template tagging

app_name = 'store'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^products/(?P<id>[0-9]+)/$',views.products,name="products"),
    url(r'^shoppingcart/$', views.shoppingcart, name="shoppingcart"),
    url(r'^add_item_to_cart/$', views.add_item_to_cart, name="add_item_to_cart"),
    url(r'^update_shoppingcart/$', views.update_shoppingcart, name="update_shoppingcart"),
    url(r'^checkout/$', views.checkout, name="checkout"),
    url(r'^order/$', views.place_order, name="order"),
    url('productdetails/(?P<id>[0-9]+)/$',views.productdetails,name="productdetails"),
] 

ishop/store/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Cart(models.Model):
    session_id = models.CharField(max_length=100)

    class Meta:
        managed = True

    def get_or_create_cart(session_key):
        return Cart.objects.get_or_create(session_id=session_key)[0]

    def get_items(self):
        return CartItem.objects.filter(cart=self)

    def update_item(self, item_id, qty):

        item = CartItem.objects.filter(cart=self, product_id=item_id)

        if item.exists():
            item = item[0]
            if qty == 0:
                item.delete()
            else:
                item.quantity = qty
                item.save()


    def add_item(self, item_id, qty):

        item = CartItem.objects.filter(cart=self, product_id=item_id)

        if item.exists():
            item = item[0]
            item.quantity += qty
        else:
            item = CartItem()
            item.cart = self
            item.quantity = qty
            item.product = Product(id = item_id)

        item.save()

    def get_total_qty(self):
        item_count = 0
        for item in self.get_items():
            item_count += item.quantity
        return item_count

    def get_total_amount(self):
        total_amount = 0
        for item in self.get_items():
            total_amount += item.line_total()
        return total_amount

    def delete_all_items(self):
        CartItem.objects.filter(cart=self).delete()

class Category(models.Model):
    ref = models.ForeignKey("self", models.DO_NOTHING, blank=True, null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(default="placeholder.png", upload_to='images',blank=True)


    class Meta:
        managed = True
        
    def __str__(self):
        return self.name


class Inventory(models.Model):
    quantity = models.IntegerField()

    class Meta:
        managed = True


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=500, blank=True, null=True)
    image1_url = models.ImageField(default="placeholder.png", upload_to='images',blank=True)
    image2_url = models.ImageField(default="placeholder.png", upload_to='images',blank=True)
    image3_url = models.ImageField(default="placeholder.png", upload_to='images',blank=True)
    image4_url = models.ImageField(default="placeholder.png", upload_to='images',blank=True)
    category = models.ForeignKey(Category, models.DO_NOTHING)
    inventory = models.ForeignKey(Inventory, models.DO_NOTHING)

    def __str__(self):
        return self.name
    class Meta:
        managed = True


class CartItem(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, models.DO_NOTHING)
    cart = models.ForeignKey(Cart, models.DO_NOTHING)

    class Meta:
        managed = True

    def line_total(self):
        return self.quantity * self.product.price

class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(User, models.DO_NOTHING, blank=True, null=True)
    cart = models.ForeignKey(Cart, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = True


class ShippingAddress(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zipcode = models.IntegerField()
    country = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True


class Payment(models.Model):
    amount = models.IntegerField()
    status = models.IntegerField()

    class Meta:
        managed = True


class Order(models.Model):
    amount = models.IntegerField()
    shipping_address = models.ForeignKey(ShippingAddress, models.DO_NOTHING)
    customer = models.ForeignKey(Customer, models.DO_NOTHING)
    payment = models.ForeignKey(Payment, models.DO_NOTHING)

    class Meta:
        managed = True


class OrderDetail(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, models.DO_NOTHING)
    order = models.ForeignKey(Order, models.DO_NOTHING)

    class Meta:
        managed = True

    def line_total(self):
        return self.quantity * self.product.price

ishop/store/forms.py
from django import forms 
from django.contrib.auth.models import User
           

class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Username'}))
    password = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter your Password'}))
    email = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Email'}))
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your First name'}))
    last_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Last name'}))

    class Meta():
        model = User
        fields = ('username','password','email','first_name','last_name')

    



      

ishop/store/views.py
from django.shortcuts import render
from store.models import Product, CartItem, Category
from django.db import transaction
from store.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from store.models import *
from django.template.defaultfilters import register
from django.db.models import Q


@register.filter(name='dict_key')
def dict_key(dict, key):
    return dict[key]


def getCategoryList():
    categorylist = {
        "subcategorylist": {}
    }

    for category in Category.objects.filter(ref__isnull=True):
        categorylist["subcategorylist"][category.name] = Category.objects.filter(
            ref__id=category.id)
        categorylist[category.name] = Category.objects.filter(
            name=category.name)
    return categorylist


def get_or_create_session_key(request):
    if not request.session.session_key:
        request.session.save()
    return request.session.session_key


def getCart(request):
    cart = Cart()
    if request.session.session_key:
        cart = Cart.get_or_create_cart(request.session.session_key)
    return cart

# Create your views here.


def index(request):
    cart = getCart(request)

    return render(request, 'store/index.html',  {'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()})


def shoppingcart(request):

    cart = getCart(request)
    if cart.get_total_amount() <= 3000:
        shippingcost = cart.get_total_amount() + 69
    else:
        shippingcost = cart.get_total_amount()
    return render(request, 'store/shoppingcart.html', {'cart_items': cart.get_items(), 'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList(), 'shippingcost': shippingcost})


def add_item_to_cart(request):

    get_or_create_session_key(request)
    cart = getCart(request)

    if request.method == 'POST' and 'request_path' in request.POST:
        item_id = int(request.POST.get('item_id'))
        qty = int(request.POST.get('add_btn'))

        cart.add_item(item_id, qty)

        return HttpResponseRedirect(request.POST.get('request_path'))

    return HttpResponseRedirect(reverse('index'))


def update_shoppingcart(request):

    cart = getCart(request)

    if request.method == "POST":

        item_id = int(request.POST.get('item_id'))
        qty = int(request.POST.get('item_qty'))

        cart.update_item(item_id, qty)
    return HttpResponseRedirect(request.POST.get('request_path'))


def checkout(request):
    cart = getCart(request)
    return render(request, 'store/checkout.html', {'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList(), 'user':request.user})


@transaction.atomic
def place_order(request):

    cart = getCart(request)

    order = Order()
    order.amount = 0
    order_details = []

    if request.method == "POST":

        # create a new order
        #order = Order()

        customer = Customer()
        customer.email = request.POST.get('emailCustomerInfo')
        customer.first_name = request.POST.get('firstnameCustomerInfo')
        customer.last_name = request.POST.get('lastnameCustomerInfo')
        customer.phone = request.POST.get('phoneCustomerInfo')
        customer.cart = cart
        if request.user.is_authenticated and request.user.is_active:
            customer.user = request.user
        customer.save()

        shipping_address = ShippingAddress()
        shipping_address.zipcode = request.POST.get(
            'zipcodeShippingInfo').replace(" ", "")
        shipping_address.street = request.POST.get('streetShippingInfo')
        shipping_address.city = request.POST.get('cityShippingInfo')
        shipping_address.country = request.POST.get('countryShippingInfo')
        shipping_address.save()

        payment = Payment()
        payment.amount = order.amount
        payment.status = 0
        payment.save()

        order.customer = customer
        order.shipping_address = shipping_address
        order.payment = payment
        order.save()

        for item in cart.get_items():
            od = OrderDetail()
            od.product = item.product
            od.quantity = item.quantity
            od.order = order
            order.amount += item.line_total()
            order_details.append(od)

        order.save()
        OrderDetail.objects.bulk_create(order_details)

        # Fake full payment
        payment.amount = order.amount
        payment.status = 1
        payment.save()

        cart.delete_all_items()

    return render(request, 'store/order.html', {'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList(), 'order': order, 'order_details': order_details})


@login_required
def special(request):
    return HttpResponse("you are logged in!,Nice!")


@login_required
def user_logout(request):
    cart = getCart(request)
    logout(request)
    request.session.save()
    cart.session_id = request.session.session_key
    cart.save()
    return HttpResponseRedirect(reverse('index'))


def register(request):

    cart = getCart(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, 'store/registration.html',
                  {'user_form': user_form,
                   'registered': registered,
                   'cart_items': cart.get_items(),
                   'item_count': cart.get_total_qty(),
                   'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()})


def user_login(request):

    cart = getCart(request)

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                cart.session_id = request.session.session_key
                cart.save()
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("someone tried to log in and failed!")
            print("username: {} and password {}".format(username, password))
            return HttpResponse('invalid login details')
    else:
        return render(request, 'store/login.html', {'cart_items': cart.get_items(), 'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()})


def products(request, id):
    cart = getCart(request)
    products = Product.objects.filter(category_id=id)
    my_dic = {'products': products, 'item_count': cart.get_total_qty(
    ), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()}
    return render(request, "store/product.html", context=my_dic)


def productdetails(request, id):

    cart = getCart(request)
    itemdetail = Product.objects.filter(id=id).first
    dict = {'itemdetail': itemdetail, 'item_count': cart.get_total_qty(
    ), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()}
    return render(request, "store/productdetails.html", context=dict)


def search(request):
    cart = getCart(request)
    if request.method == 'GET':
        searchresult = request.GET.get('searchtext')
        return_url = "?searchtext={0}".format(searchresult)
        if searchresult:
            products = Product.objects.filter(
                Q(name__icontains=searchresult) | Q(description__icontains=searchresult))
            return render(request, 'store/searchpage.html', {'return_url': return_url, 'products': products, 'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()})
        else:
            print("No matching item found")
            return render(request, 'store/searchpage.html', {'item_count': cart.get_total_qty(), 'total_amount': cart.get_total_amount(), 'categorylist': getCategoryList()})

ishop/templates/store/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script defer src="{% static 'javascript/basic.js' %}"></script>

    <!--  <script src="https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script> -->

</head>

<body>
    <nav id="navbar" class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid justify-content-md-center">
            <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/ishop.png' %}"
                    style="width:150px;height:80px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <form action="/search" method="GET" class="form-inline" style="width:40%">
                    <div class="wrap">
                        <div class="search">
                           <input type="text" class="searchTerm" name="searchtext" placeholder="What are you looking for?">
                           <button type="submit" class="searchButton">
                             <i class="fa fa-search"></i>
                          </button>
                        </div>
                     </div>
                </form>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link">
                            {% if user.is_authenticated %}
                            Welcome <b> {{user.first_name}} </b>
                            {% endif %}
                        </a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link"
                            aria-current="page" href="{% url 'admin:index' %}"><b>Admin</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index' %} active {% endif %}"
                            aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'products' %} active {% endif %}"
                            href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Products
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for category in categorylist.subcategorylist %}
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="#">
                                    {{ category }} </a>
                                <ul class="dropdown-menu">
                                    {% for subcategory in categorylist.subcategorylist|dict_key:category %}
                                    <li><a class="dropdown-item"
                                            href="{% url 'store:products' subcategory.id %}">{{subcategory.name}}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a class="nav-link {% if request.resolver_match.url_name == 'footercontainer1' %} active {% endif %}"
                            href="#footercontainer1">Contact</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link {% if request.resolver_match.url_name == 'logout' %} active {% endif %}"
                            href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == "register" %}
                            active {% endif %}" href="{% url 'store:register' %}">Register</a></li>
                    <li><a class="nav-link {% if request.resolver_match.url_name == 'user_login' %} active {% endif %}"
                            href="{% url 'store:user_login' %}">Login</a></li>
                    {% endif %}

                    <li class="nav-item">
                        <a href="{% url 'store:shoppingcart' %}">
                            <img id="cart-icon" src="{% static 'images/cart3.png' %}">
                        </a>
                        <span id="cart-price"> {% if total_amount > 0 %} {{ total_amount }} {% endif %} <span>
                                <span id="cart-total" style="position:absoulte;top:-5px">{{ item_count }}<span>
                    </li>
                </ul>

            </div>
        </div>
    </nav>


    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    <br><br><br> <br><br><br> <br><br><br>
    <br><br><br>


    <div class="footercontainer" id="footercontainer1">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col col-lg-4">
                    <h5>Opening hours:</h5>
                    <h6><b>Mon- Sat:</b> 10.00-17.00</h6>
                    <h6><b>Sunday:</b> Closed</h6>
                </div>
                <div class="col col-lg-4">
                    <h5><img id="cart-icon" src="{% static 'images/location.png' %}">Address:</h5>
                    <h6>Galärvarvsvägen 14, <br> 115 21 Stockholm <br> Sweden</h6> <br>
                    <h6>8712 W Linebaugh Ave <br> Citrus Park, Florida <br> USA</h6> <br>
                </div>
                <div class="col col-lg-4">
                    <h5>Reach us:</h5>
                    <h6><img id="cart-icon" src="{% static 'images/mail.png' %}">Email us: customercare@ishop.se</h6>
                    <br>
                    <h6><img id="cart-icon" src="{% static 'images/call.png' %}">Call us: 0794437354</h6>
                </div>
            </div>
        </div>
    </div>
    <footer class="bg-light text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-2">
                <!-- Facebook -->
                <a class="btn text-white btn-floating" style="background-color: #3b5998;"
                    href="https://www.facebook.com/" role="button"><i class="fab fa-facebook-f fa-1x"
                        style="height:5px;width:8px;"></i></a>


                <!-- Instagram -->
                <a class="btn text-white btn-floating" style="background-color: #ac2bac;"
                    href="https://www.instagram.com" role="button"><i class="fab fa-instagram fa-1x"
                        style="height:5px;width:8px;"></i></a>

                <!-- Youtube-->
                <a class="btn text-white btn-floating" style="background-color: red;" href="https://www.youtube.com/"
                    role="button"><i class="fab fa-youtube fa-1x" style="height:5px;width:8px;"></i></a>

            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center py-0.5" style="background-color:grey;height:20px ">
            <p class="footertag"><em> © 2022 Copyright: ishop</em></p>

        </div>
        <!-- Copyright -->
    </footer>
    {% block scripts %}
    {% endblock %}

</body>

</html>

ishop/templates/store/collections.html
{% load static %}


<div class="container">
    <h4>Main Categories</h4>
    <hr>


    <div class="row md-8">
        {% for item in categorylist.subcategorylist %}
        <div class="col md-2">
            <div class="product-thumbnail1">
                <div class="product-thumbnail1-hover">
                    {% for category in categorylist|dict_key:item %}
                    <a href="{{ category.name }}" class="category text-dark" style="text-decoration:none ;"><img
                            src="{{ category.image.url }}" class="img-thumbnail">
                       <center> {{ category.name }}</center></a>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="content-section">
        <div class="js-content-wrapper">

        </div>
    </div>

    <div id="external-content">

        {% for item in categorylist.subcategorylist %}
        {% for category in categorylist|dict_key:item %}

        <div id="{{category.name}}">
            <div class="row mx-auto">
                <div class="col mx-auto">
                    <br>
                    <h5 class="active1">Under {{category.name}}</h5>
                    <div class="subproduct-thumbnail">

                        {% for subcategory in categorylist.subcategorylist|dict_key:item %}
                        <div style="display: inline-block;margin-top: 5px;margin-right: 20px;color: brown;">
                            <div class="product-thumbnail-hover">
                                <a href="{% url 'store:products' subcategory.id %}" class="acenter text-dark"
                                    style="text-decoration:none;"> <img src="{{ subcategory.image.url }}"
                                        class="rounded" style="height:100px;border:3"><br><br>
                                    <center>{{ subcategory.name }}</center> </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
        {% endfor %}
        {% endfor %}
    </div>

</div>
</div>

ishop/templates/store/index.html
{% extends "store/base.html" %}
<title>IndexPage</title>
{% block body_block %}
{% include 'store/collections.html' %}
{% endblock %}

ishop/templates/store/login.html
{% extends "store/base.html" %}

{% block body_block %}      

<div class="jumbotron">
  <h1>Please Login</h1>
  <br>
  <br>
  <form action="{% url 'store:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text"name="username"placeholder="Enter Username">
    <br>
    <br>
    <label for="password">Password</label>
    <input type="password"name="password"placeholder="password">
    <br>
    <br>
    <input type="submit" style="background-color:green;color:white;width:80px;
height:40px;" value="login">
  </form>
</div>
<br>
Not Registerd? Sign Up <a href="{% url 'store:register' %}">Here...</a>
{% endblock %}

ishop/templates/store/product.html
{% extends "store/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<title> Products </title>
{% block body_block %}
<h3> Product Page </h3>
<div class="row">
    {% for item in products %}
    <div class="col-lg-4 bg-image hover-zoom">
        <div class="product-thumbnail">
            <div class="product-thumbnail-hover">
                <img class="thumbnail" src="{{ item.image1_url.url }}">
                <div class="box-element product">
                    <h6> {{item.name}} </h6>
                    <hr>

                    <form action="{% url 'store:add_item_to_cart' %}" method="post">
                        {% csrf_token %}
                        <div onclick="productCalculate('{{item.id}}','-')" class="btn btn-outline-secondary">&minus;</div>
                        <div style="pointer-events: none" id="result_div{{ item.id }}" class="btn btn-outline-secondary">1</div>
                        <div onclick="productCalculate('{{item.id}}','+')" class="btn btn-outline-secondary">&plus;</div>
                        <input type="hidden" name="request_path" value="{{request.path}}">
                        <input type="hidden" name="item_id" value="{{item.id}}">
                        <button id="add_btn{{item.id}}" type="submit" name='add_btn' value='1' class="btn btn-outline-secondary add-btn"> Add to Cart </button>
                    </form>
                    <br />
                    <a class="btn btn-outline-success" href="{% url 'store:productdetails' item.id %}"> View </a>
                    <h6 style="display:inline-block; float: right; padding-top:8px"> {{item.price}} SEK</h6>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ishop/templates/store/registration.html
<!DOCTYPE html>
{% extends "store/base.html" %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for Registration</h1>
    {% else %}
    <h2> Registration Form </h2>
    <br>
    <div class="form-group">
    <form enctype ="multipart/form-data" style="width:60%" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" style="background-color:green;color:white;width:80px;
height:40px;" value="Register">
    </form>
    </div>
    {% endif %}
</div>
{% endblock %}

ishop/templates/store/searchpage.html
{% extends "store/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<title> Products </title>
{% block body_block %}
<h3> Product Page </h3>
<div class="row">
    {% for item in products %}
    <div class="col-lg-4 bg-image hover-zoom">
        <div class="product-thumbnail">
            <div class="product-thumbnail-hover">
                <img class="thumbnail" src="{{ item.image1_url.url }}">
                <div class="box-element product">
                    <h6> {{item.name}} </h6>
                    <hr>

                    <form action="{% url 'store:add_item_to_cart' %}" method="post">
                        {% csrf_token %}
                        <div onclick="productCalculate('{{item.id}}','-')" class="btn btn-outline-secondary">&minus;</div>
                        <div style="pointer-events: none" id="result_div{{ item.id }}" class="btn btn-outline-secondary">1</div>
                        <div onclick="productCalculate('{{item.id}}','+')" class="btn btn-outline-secondary">&plus;</div>
                        <input type="hidden" name="request_path" value="{{request.path}}{{return_url}}">
                        <input type="hidden" name="item_id" value="{{item.id}}">
                        <button id="add_btn{{item.id}}" type="submit" name='add_btn' value='1' class="btn btn-outline-secondary add-btn"> Add to Cart </button>
                    </form>
                    <br />
                    <a class="btn btn-outline-success" href="{% url 'store:productdetails' item.id %}"> View </a>
                    <h6 style="display:inline-block; float: right; padding-top:8px"> {{item.price}} SEK</h6>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}